services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
